name: Log Traffic to CSV

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  log_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install requests

      - run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add traffic_log.csv
          git commit -m "Update traffic log [skip ci]" || echo "No changes"
          git push
